- wasted-app/Documentation/DB/README.md
> Feature create db as file

- wasted-app/Controller/Entities/Coords.cs
- wasted-app/Controller/Entities/Distances.cs
- wasted-app/Controller/Entities/Restaurant.cs
- wasted-app/Controller/Interfaces/Repositories/IFoodRepository.cs
- wasted-app/Controller/Interfaces/Repositories/IRestaurantRepository.cs
- wasted-app/Controller/Interfaces/Services/IAuthService.cs
- wasted-app/Controller/Interfaces/Services/IFoodService.cs
- wasted-app/Controller/Interfaces/Services/IRestaurantService.cs
- wasted-app/Controller/Services/FoodService.cs
- wasted-app/Controller/Services/RestaurantService.cs
- wasted-app/DB/Data/Test/Foods.json
- wasted-app/DB/Data/Test/Restaurants.json
- wasted-app/Model/Repositories/BaseRepository.cs
- wasted-app/Model/Repositories/FoodRepository.cs
- wasted-app/Model/Repositories/RestaurantRepository.cs
> Feature complete crud

- wasted-app/Controller/Entities/Coords.cs
- wasted-app/Controller/Entities/Mail.cs
- wasted-app/Controller/Entities/Password.cs
- wasted-app/Controller/Entities/Restaurant.cs
- wasted-app/Controller/Services/RestaurantService.cs
- wasted-app/DB/Data/Production/Restaurants.json
- wasted-app/Documentation/Class Diagram/README.md
- wasted-app/Documentation/DB/README.md
- wasted-app/Model/Repositories/RestaurantRepository.cs
- wasted-app/RestaurantLogInControl.cs
- wasted-app/RestaurantRegistrationControl.cs
- wasted-app/Utilities/Validator.cs
Restaurants can now register and login into their accounts
> validate restaurant email and password with login/registration 

- wasted-app/RestaurantControl.Designer.cs
- wasted-app/RestaurantControl.cs
- wasted-app/RestaurantListControl.Designer.cs
- wasted-app/RestaurantListControl.cs
- wasted-app/RestaurantViewFoodControl.Designer.cs
- wasted-app/RestaurantViewFoodControl.cs
- wasted-app/RestaurantViewFoodControl.resx
- wasted-app/ViewFoodControl.Designer.cs
- wasted-app/ViewFoodControl.cs
- wasted-app/ViewFoodControl.resx
Added a screen for users to see what food items are available for a selected restaurant
> View restaurant food

- wasted-app/Controller/DTOs/BaseDto.cs
- wasted-app/Controller/DTOs/RestaurantDto.cs
- wasted-app/Controller/Interfaces/Services/IAuthService.cs
- wasted-app/Controller/Interfaces/Services/IFoodService.cs
- wasted-app/Controller/Interfaces/Services/IRestaurantService.cs
- wasted-app/Controller/Interfaces/Services/ITypeOfFoodService.cs
- wasted-app/Controller/Services/FoodService.cs
- wasted-app/Controller/Services/RestaurantService.cs
- The goal of this pr is to use **RestaurantDTO instead of Restaurant** so that users cannot retrieve confidential information like passwords from restaurants entities. 
- I also changed the services to use this object and I **removed the GetByMail method** of the service interface, because a user should not be able to use this method. If they had the mail they could retrieve the restaurant, so it should not be used on the UI.
Closes #56 
Closes #57
> Add restaurant dto class

- wasted-app/Controller/Comparers/Food/FoodCheaperFirst.cs
- wasted-app/Controller/Comparers/Food/FoodNewFirst.cs
- wasted-app/Controller/Entities/ListOfFood.cs
**Goal:** sort foods
**Sorting ways:** 
- By price
- By date
**Requirements**:
- Extension methods
- Implement a .net interface
> Sort foods

- backend/Contracts/DTOs/RestaurantDto.cs
- backend/Domain/Entities/Coords.cs
- backend/Domain/Entities/Restaurant.cs
- backend/Domain/Helpers/CoordsHelper.cs
Added exceptions where I thought they were needed to prevent random bugs from happening.
> Exceptions

- backend/ConsoleApp/Program.cs
- backend/Contracts/DTOs/FoodResponse.cs
- backend/Domain/Entities/Food.cs
- backend/Domain/Entities/ListOfFood.cs
- backend/Persistence/DB/Data/Test/Foods.json
- backend/Persistence/DB/Data/Test/Restaurants.json
- backend/Services/Services/FoodService.cs
- backend/WebApi/Controllers/FoodController.cs
- backend/WebApi/Controllers/RestaurantController.cs
Implemented price decrease. I don't know if it is the optimal solution, but currently the client can pick price decrease type (either "AMOUNT" or "PERCENT") by which current price is calculated and returned in a FoodResponse dto.
> Price decrease

- backend/Persistence/DB/Data/Test/Foods.json
- backend/Persistence/DB/Data/Test/Restaurants.json
- backend/Persistence/DB/Data/Test/TypesOfFood.json
Added more suitable restaurants to the DB and made all the passwords follow the same rules:
RestaurantName123!             //Restaurant name is without spaces
If the password is shorter then minimum size the end is filled with exclamation marks until minimum size
> Redid the test data

- backend/Contracts/DTOs/FoodResponse.cs
- backend/Domain/Entities/Food.cs
- backend/Persistence/DB/Data/Test/Foods.json
Added minimum price to food items to fix negative current price bug.
Added description to food items.
> Minimum food price and description properties

- backend/Domain/Entities/Coords.cs
- backend/Domain/Helpers/CoordsHelper.cs
- backend/WebApi/Controllers/FoodController.cs
- backend/WebApi/Controllers/RestaurantController.cs
- backend/WebApi/Helpers/EntitySorter.cs
- backend/WebApi/Helpers/InputValidator.cs
Added optional parameters to existing endpoint so that user can fetch already sorted objects.
> Sorted restaurant and food endpoints

- backend/WebApi/Controllers/RestaurantController.cs
- frontend/wasted-app/src/api/interfaces.ts
- frontend/wasted-app/src/api/restaurant.ts
- frontend/wasted-app/src/screens/restaurant-login/restaurant-login.tsx
- frontend/wasted-app/src/screens/restaurant/profile/interfaces.ts
- frontend/wasted-app/src/screens/restaurant/profile/profile.tsx
Closes #179 
This screen shows the information of the restaurant and allow the user to update it. Right now it does not change the image nor the password.
- We need to add a new endpoint to change the passwords.
- If we change the address, the coords won´t correspond to the updated address, maybe in a real version we should use some API from Google maps or something like that.
- If we press cancel button, the form is filled with the original restaurant data.
> Restaurant profile

- backend/Contracts/DTOs/RestaurantDto.cs
- backend/Persistence/DB/Data/Test/Foods.json
- backend/WebApi/Controllers/RestaurantController.cs
- frontend/wasted-app/android/app/build.gradle
- frontend/wasted-app/android/app/src/main/AndroidManifest.xml
- frontend/wasted-app/ios/Podfile.lock
- frontend/wasted-app/ios/wastedapp/Info.plist
- frontend/wasted-app/package-lock.json
- frontend/wasted-app/package.json
- frontend/wasted-app/src/api/food.ts
- frontend/wasted-app/src/api/interfaces.ts
- frontend/wasted-app/src/api/restaurant.ts
- frontend/wasted-app/src/components/horizontal-list/horizontal-list.tsx
- frontend/wasted-app/src/components/sections/cheapest-food/cheapest-food.tsx
- frontend/wasted-app/src/components/sections/latest-food/latest-food.tsx
- frontend/wasted-app/src/components/sections/near-restaurants/near-restaurants.tsx
- frontend/wasted-app/src/components/sections/popular-restaurants/popular-restaurants.tsx
- frontend/wasted-app/src/screens/food-info/food-info.tsx
- frontend/wasted-app/src/utils/coordinates.ts
Now in user's home screen the foods and restaurants are actually sorted by time, location and price. To get user's location I've installed a very simple library
> User home fetch sorted items

- backend/Contracts/DTOs/RestaurantDto.cs
- backend/Services/Interfaces/IRestaurantService.cs
- backend/Services/Services/RestaurantService.cs
- backend/WebApi/Controllers/RestaurantController.cs
- backend/WebApi/Helpers/EntitySorter.cs
- backend/WebApi/Helpers/InputValidator.cs
> Food count

- backend/Services/Services/RestaurantService.cs
- backend/WebApi/Controllers/RestaurantController.cs
Changed register endpoint to return different response codes if the restaurant mail is already used and if the password is invalid. This helps frontend differentiate between the responses.
This can be improved when custom exceptions are implemented
> Added different error codes in register endpoint

- backend/WebApi/package-lock.json
- frontend/wasted-app/.gitignore
- frontend/wasted-app/credentials.ts
- frontend/wasted-app/index.js
- frontend/wasted-app/package-lock.json
- frontend/wasted-app/package.json
- frontend/wasted-app/src/api/interfaces.ts
- frontend/wasted-app/src/api/restaurant.ts
- frontend/wasted-app/src/components/password-input/interfaces.ts
- frontend/wasted-app/src/components/password-input/password-input.tsx
- frontend/wasted-app/src/credentials.ts
- frontend/wasted-app/src/screens/restaurant-login/restaurant-login.tsx
- frontend/wasted-app/src/screens/restaurant-login/restaurant-registration/restaurant-registration.tsx
- Added ability for restaurants to register with their info
- No frontend validation for passwords (passwords still have to match)
- Ability to show password
- Only 2 errors: ("check required fields" and "Restaurant with this email exists")
- Fetches coordinates from Address string
- Requires image url
- Sends email to specified email after registering
> Restaurant registration

- backend/Domain/Entities/Coords.cs
- backend/Domain/Entities/Mail.cs
- backend/Domain/Entities/Password.cs
- backend/Services/Exceptions/AuthorizationException.cs
- backend/Services/Exceptions/EntityNotFoundException.cs
- backend/Services/Services/FoodService.cs
- backend/Services/Services/RestaurantService.cs
- backend/WebApi/Controllers/FoodController.cs
- backend/WebApi/Controllers/RestaurantController.cs
- backend/WebApi/Helpers/InputValidator.cs
Added new exceptions, did a little bit of refactoring. Please review if everything is fine, because I didn't test everything thoroughly.
> Exception refactor

- backend/Contracts/DTOs/RestaurantDto.cs
- backend/Contracts/DTOs/RestaurantRegisterRequest.cs
- backend/Domain/Entities/Food.cs
- backend/Domain/Entities/Restaurant.cs
- backend/Services/Services/FoodService.cs
- backend/WebApi/Controllers/FoodController.cs
Fixed a bug where imageUrl would be set to empty string instead of the default url.
Handled and uncaught exception in Food registration.
> Fix url bug

- Requirements.md
Improved docs. Added explanations and links to check out.
> Improve requirement docs

- .github/workflows/backend.yml
- README.md
- backend/ConsoleApp/Program.cs
- backend/README.md
- backend/wasted-app.sln
I set up some github actions to pass the tests whenever we do a pr to the backend directory.
> Testing ga

- frontend/wasted-app/android/app/src/main/AndroidManifest.xml
- frontend/wasted-app/ios/Podfile
- frontend/wasted-app/ios/Podfile.lock
- frontend/wasted-app/ios/wastedapp.xcodeproj/project.pbxproj
- frontend/wasted-app/ios/wastedapp/AppDelegate.m
- frontend/wasted-app/package-lock.json
- frontend/wasted-app/package.json
- frontend/wasted-app/src/components/foods-list/foods-list.tsx
- frontend/wasted-app/src/components/map/index.ts
- frontend/wasted-app/src/components/map/interfaces.ts
- frontend/wasted-app/src/components/map/map.tsx
- frontend/wasted-app/src/components/sections/cheapest-food/cheapest-food.tsx
- frontend/wasted-app/src/components/sections/latest-food/latest-food.tsx
- frontend/wasted-app/src/hooks/use-previous.ts
- frontend/wasted-app/src/screens/food-info/food-info.tsx
- frontend/wasted-app/src/screens/restaurant-info/restaurant-info.tsx
- frontend/wasted-app/src/screens/restaurant-login/restaurant-registration/restaurant-registration.tsx
- frontend/wasted-app/src/screens/restaurant/addFood/addFood.tsx
- frontend/wasted-app/src/services/navigation.ts
Closing #113 
- Added map in restaurant registration which updates after address is input. It also changes the address field to the formatted address received from Google Maps API, making it much tidier. In this example I input "gril londo vil", it shows suggestion and then and after selecting it has changed to full address - "Vilniaus g. 33, Vilnius 01402, Lithuania"
- Added map in restaurant info to show where restaurant is located on google maps
- Also made food info as a screen instead of a modal as it was causing issues when going: food info modal > restaurant info > restaurants' food list > food info modal, then dismissing the food info modal caused it to go back all the way back to the home screen. Now it shows the food info as a modal only when going from restaurant's food list
> Mapview integration

- frontend/wasted-app/index.js
- frontend/wasted-app/package-lock.json
- frontend/wasted-app/package.json
- frontend/wasted-app/src/actions/location.ts
- frontend/wasted-app/src/actions/restaurant.ts
- frontend/wasted-app/src/hooks/location.ts
- frontend/wasted-app/src/reducers/index.ts
- frontend/wasted-app/src/reducers/location.ts
- frontend/wasted-app/src/reducers/restaurant.ts
- frontend/wasted-app/src/screens.tsx
- frontend/wasted-app/src/screens/restaurant/addFood/addFood.tsx
- frontend/wasted-app/src/screens/user/home/home.tsx
- frontend/wasted-app/src/selectors/location.ts
- frontend/wasted-app/src/selectors/restaurant.ts
- frontend/wasted-app/src/store/index.ts
- frontend/wasted-app/src/typings/redux.ts
- Setup Redux to store some commonly used state in the whole app like location or logged in restaurant's credentials (in future)
- Also now show error in home screen if user rejected location permissions
> Redux setup

- backend/WebApi/Middleware/ErrorHandlingMiddleware.cs
- backend/WebApi/Startup.cs
- backend/WebApi/WebApi.csproj
Add a middleware to catch the exceptions and print them into a file in the server.
>
> Add error middleware and log into a file in the server

- backend/Domain/Entities/Entity.cs
- backend/Persistence/DatabaseContext.cs
- backend/Persistence/Mappers/FoodMapper.cs
Fixed bug where user couldn't set custom created at date for foods when registering them
> Fixed Created At Date bug
